import { useEffect } from 'react'
import TopNav from "../components/navigation/TopNav"
import Head from 'next/head'
import { useRouter } from 'next/router'
import NProgress from "nprogress"



const MainLayout = ({ children }) => {
    const router = useRouter();

    useEffect(() => {
        const handleStart = (url) => {
            console.log(`Loading: ${url}`)
            NProgress.start()
        }
        const handleStop = () => {
            NProgress.done()
        }

        router.events.on('routeChangeStart', handleStart)
        router.events.on('routeChangeComplete', handleStop)
        router.events.on('routeChangeError', handleStop)

        return () => {
        router.events.off('routeChangeStart', handleStart)
        router.events.off('routeChangeComplete', handleStop)
        router.events.off('routeChangeError', handleStop)
        }
    }, [router])

    return (
        <>
            <Head>
                <title>Tutorial App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <TopNav/>
            <main className="container-2xl flex-1">{children}</main>
        </>
    )
}

export default MainLayout
